"""LLM 域错误码定义。"""

from enum import StrEnum


class LLMErrorCode(StrEnum):
    """llm-service 域前缀错误码。"""

    PROVIDER_NOT_FOUND = "LLM_PROVIDER_NOT_FOUND"
    PROVIDER_UNREACHABLE = "LLM_PROVIDER_UNREACHABLE"
    PROVIDER_IN_USE = "LLM_PROVIDER_IN_USE"
    PROVIDER_SLUG_CONFLICT = "LLM_PROVIDER_SLUG_CONFLICT"
    MODEL_NOT_FOUND = "LLM_MODEL_NOT_FOUND"
    SLOT_NOT_CONFIGURED = "LLM_SLOT_NOT_CONFIGURED"
    SLOT_INVALID_TYPE = "LLM_SLOT_INVALID_TYPE"
    API_KEY_INVALID = "LLM_API_KEY_INVALID"
    ENCRYPTION_ERROR = "LLM_ENCRYPTION_ERROR"
    INVALID_PRESET = "LLM_INVALID_PRESET"
    UPSTREAM_ERROR = "LLM_UPSTREAM_ERROR"
    ALL_MODELS_FAILED = "LLM_ALL_MODELS_FAILED"
