"""AUTH 域错误码。"""

from enum import StrEnum


class AuthErrorCode(StrEnum):
    """用户认证服务错误码。"""

    INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    EMAIL_EXISTS = "AUTH_EMAIL_EXISTS"
    USER_INACTIVE = "AUTH_USER_INACTIVE"
    INVALID_TOKEN = "AUTH_INVALID_TOKEN"
    TOKEN_TYPE_MISMATCH = "AUTH_TOKEN_TYPE_MISMATCH"
    API_KEY_NOT_FOUND = "AUTH_API_KEY_NOT_FOUND"
    REGISTRATION_DISABLED = "AUTH_REGISTRATION_DISABLED"
